granadilla/urls.py
# -*- coding: utf-8 -*-
#
# django-granadilla
# Copyright (C) 2009-2012 Bolloré telecom
# See AUTHORS file for a full list of contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.urls import path, re_path

from . import views

app_name = 'granadilla'
urlpatterns = [
    path('', views.index, name='index'),
    path('devices/', views.device_list, name="device_list"),
    path('devices/create/', views.device_create, name="device_create"),
    re_path(r'^devices/(?P<device_login>[^/]+)/$', views.device_attr, name="device_details"),
    re_path(r'^devices/(?P<device_login>[^/]+)/password/$', views.device_password, name='device_password'),
    re_path(r'^devices/(?P<device_login>[^/]+)/delete/$', views.device_delete),
    path('groups/', views.groups, name='groups'),
    re_path(r'^group/(?P<slug>.*)/print/$', views.group_print, name='group_print'),
    re_path(r'^group/(?P<slug>.*)/$', views.group, name='group'),
    re_path(r'^user/(?P<uid>.*)/card/$', views.user_card, name='user_card'),
    re_path(r'^user/(?P<uid>.*)/photo/$', views.photo),
    re_path(r'^user/(?P<uid>.*)/photo/delete/$', views.photo_delete),
    re_path(r'^user/(?P<uid>.*)/$', views.user, name='user'),
    path('password/', views.ChangePassword, name='change_password'),
]

granadilla_webapp/urls.py
from django.urls import include, path

from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    # accounts
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='auth-logout'),

    # admin interface
    path('admin/', admin.site.urls),

    # granadilla
    path('', include('granadilla.urls')),
]

granadilla/forms.py
# -*- coding: utf-8 -*-
#
# django-granadilla
# Copyright (C) 2009-2012 Bolloré telecom
# See AUTHORS file for a full list of contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from . import models
from django import forms
from django.utils.translation import gettext_lazy as _

from zxcvbn_password.fields import PasswordField, PasswordConfirmationField


class LdapDeviceForm(forms.Form):

    name = forms.CharField(label=_("Name (e.g 'laptop')"), max_length=42)

    def __init__(self, target_user, instance=None, *args, **kwargs):
        self.target_user = target_user
        assert instance is None
        super(LdapDeviceForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name']
        login = '%s_%s' % (self.target_user.username, name)

        if models.LdapDevice.objects.filter(login=login).exists():
            raise forms.ValidationError(_("A device with name %s already exists") % name)

        return name

    def save(self, commit=True):
        # target_user might be a Django User object
        user = models.LdapUser.objects.get(username=self.target_user.username)
        name = self.data['name']
        login = '%s_%s' % (user.username, name)

        device = models.LdapDevice(
            owner_username=user.username,
            owner_dn=user.dn,
            login=login,
            name=name,
        )
        device.set_password()
        device.save()

        return device


class LdapUserForm(forms.ModelForm):
    new_photo = forms.ImageField(required=False, label=_("Photo"))

    def save(self, commit=True):
        contact = super(LdapUserForm, self).save(False)
        photo = self.cleaned_data['new_photo']
        if hasattr(photo, 'read'):
            contact.photo = photo.read()
        if commit:
            contact.save()
        return contact

    class Meta:
        model = models.LdapUser
        fields = ('phone', 'mobile_phone', 'internal_phone', 'new_photo')


class LdapUserPassForm(forms.Form):
    current_pass = forms.CharField(label='Current password', max_length=150, widget=forms.PasswordInput())
    new_pass_1 = PasswordField()
    new_pass_2 = PasswordConfirmationField(confirm_with='new_pass_1')

    def clean(self):
        cleaned_data = super(LdapUserPassForm, self).clean()
        new_pass_1 = cleaned_data.get("new_pass_1")
        if new_pass_1 is not None:
            if not self.user.check_password(self.cleaned_data['current_pass']):
                raise forms.ValidationError("Invalid Password!")
        check = models.check_password_strength(
            new_pass_1,
            [self.user.username, self.user.first_name, self.user.last_name],
        )
        if not check.good:
            raise forms.ValidationError(str(check.message))
        return cleaned_data

    def save(self):
        self.user.set_password(self.cleaned_data['new_pass_2'])
        self.user.save()
        return self.user

    def __init__(self, *args, user, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

granadilla/views.py
# -*- coding: utf-8 -*-
#
# django-granadilla
# Copyright (C) 2009-2012 Bolloré telecom
# See AUTHORS file for a full list of contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

import time

from .conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import get_object_or_404, redirect, render
from django.template import RequestContext
from django.utils.http import http_date
from django.views.static import was_modified_since
from django.views import generic as generic_views
from django.views.generic.edit import FormView
from granadilla.templatetags.granadilla_tags import granadilla_media
from granadilla.forms import LdapDeviceForm, LdapUserForm, LdapUserPassForm
from . import models
from . import vcard
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _


def can_write(user, entry):
    """
    Check whether a user can write an LDAP entry.
    """
    can_edit = user.username == entry.username or user.is_superuser
    for group in user.groups.all():
        if group.name in settings.GRANADILLA_ADMIN_GROUPS:
            return True
    return can_edit


def get_contacts(user):
    base_dn = "ou=%s,%s" % (user.username, settings.GRANADILLA_CONTACTS_DN)
    return models.LdapContact.scoped(base_dn)


def user_vcard(user):
    """Return the vCard for a contact."""
    card = vcard.VCard()
    card['kind'] = 'individual'
    card['names'] = [
        [user.first_name],
        [user.last_name],
        [],  # Additional names
        [],  # Honorific prefixes
        [],  # Honorific suffixes
    ]
    card['full_name'] = user.full_name
    card['email'] = user.email
    card['org'] = getattr(user, 'organization', '')
    card['phone'] = user.phone
    card['cell'] = user.mobile_phone

    # send response
    response = HttpResponse(card.render_bytes(), "text/x-vcard; charset=utf-8")
    response['Content-Disposition'] = "attachment; filename=%s.vcf" % user.pk.replace(' ', '')
    return response


@login_required
def index(request, template_name='granadilla/facebook.html'):
    return group(request, pk=settings.GRANADILLA_USERS_GROUP)


@login_required
def contact_card(request, contact_id):
    contact = get_contacts(request.user).objects.get(pk=contact_id)
    return user_vcard(contact)


class DeviceACLMixin(object):
    def get_queryset(self):
        user = self.request.user

        if user.is_superuser:
            return models.LdapDevice.objects.order_by('owner_username')
        else:
            return models.LdapDevice.objects.filter(owner_username=user.username)


class DeviceCreate(generic_views.CreateView):
    """
    Creating a new device
    """
    model = models.LdapDevice
    template_name = 'granadilla/device.html'

    form_class = LdapDeviceForm

    def get_form_kwargs(self):
        kwargs = super(DeviceCreate, self).get_form_kwargs()
        kwargs['target_user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('granadilla:device_list')


device_create = login_required(DeviceCreate.as_view())


class DevicePassword(DeviceACLMixin, generic_views.DetailView):
    """
    Generating a new password
    """
    model = models.LdapDevice
    template_name = 'granadilla/device_password.html'

    slug_field = 'login'
    slug_url_kwarg = 'device_login'
    context_object_name = 'device'

    http_method_names = ['get', 'post']

    def post(self, request, *args, **kwargs):
        # Set self.object, expected by Django
        device = self.object = self.get_object()
        password = device.set_password()
        device.save()

        context = self.get_context_data(object=device)
        context['password'] = password
        return self.render_to_response(context)


device_password = login_required(DevicePassword.as_view())


class DeviceDelete(DeviceACLMixin, generic_views.DeleteView):
    """
    Deleting a device
    """
    model = models.LdapDevice
    template_name = 'granadilla/device_delete.html'

    slug_field = 'login'
    slug_url_kwarg = 'device_login'

    def get_success_url(self):
        return reverse('granadilla:device_list')


device_delete = login_required(DeviceDelete.as_view())


class DeviceAttrView(DeviceACLMixin, generic_views.DetailView):
    """
    Displaying the device's attribute
    """
    model = models.LdapDevice
    template_name = 'granadilla/device_attr.html'

    slug_field = 'login'
    slug_url_kwarg = 'device_login'
    context_object_name = 'device'


device_attr = login_required(DeviceAttrView.as_view())


class DeviceListView(DeviceACLMixin, generic_views.ListView):
    """
    Displaying the list of devices
    """
    model = models.LdapDevice
    template_name = 'granadilla/device_list.html'
    context_object_name = 'devices'


device_list = login_required(DeviceListView.as_view())


class GroupView(generic_views.DetailView):
    model = models.LdapGroup
    template_name = 'granadilla/group.html'
    printable = False
    slug_field = 'name'

    def get_context_data(self, **kwargs):
        ctxt = super(GroupView, self).get_context_data(**kwargs)
        ctxt.update({
            'printable': self.printable,
            'home': self.object.name == settings.GRANADILLA_USERS_GROUP,
            'group': self.object,
            'members': models.LdapUser.objects.filter(username__in=self.object.usernames),
        })
        return ctxt


group = login_required(GroupView.as_view())


class ChangePasswordView(SuccessMessageMixin, FormView):
    """
    function to change the user's password
    """
    model = models.LdapUser

    template_name = 'granadilla/change_password.html'
    form_class = LdapUserPassForm
    success_url = '/devices'
    success_message = "Congratulations, your password has been successfully changed."

    def get_context_data(self, **kwargs):
        context = super(ChangePasswordView, self).get_context_data(**kwargs)
        context['form_user'] = self.get_form()
        return context

    def form_valid(self, form):
        form.save()
        return super(ChangePasswordView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.model.objects.get(username=self.request.user.username)
        return kwargs

    def get_success_message(self, cleaned_data):
        success_message = _(self.success_message)
        return success_message


ChangePassword = login_required(ChangePasswordView.as_view())


class PrintableGroupView(GroupView):
    """
    Display a printable list of users belonging to a group.
    """
    printable = True


group_print = login_required(PrintableGroupView.as_view())


class GroupsView(generic_views.ListView):
    """
    Display the list of groups.
    """
    model = models.LdapGroup
    template_name = 'granadilla/group_list.html'


groups = login_required(GroupsView.as_view())


@login_required
def photo(request, uid):
    now = time.time()
    max_age = 1800
    if not was_modified_since(request.META.get('HTTP_IF_MODIFIED_SINCE'), now - max_age):
        return HttpResponseNotModified()

    user = get_object_or_404(models.LdapUser, pk=uid)
    if not user.photo:
        return HttpResponseRedirect(granadilla_media('img/unknown.png'))
    response = HttpResponse()
    response['Cache-Control'] = 'max-age=%i' % max_age
    response['Content-Length'] = len(user.photo)
    response['Content-Type'] = 'image/jpeg'
    response['Last-Modified'] = http_date(now)
    response.write(user.photo)
    return response


def photo_delete(request, uid):
    user = get_object_or_404(models.LdapUser, pk=uid)
    if not can_write(request.user, user):
        raise PermissionDenied

    if request.method == 'POST':
        user.photo = ''
        user.save()
        return redirect(reverse(index))
    else:
        return render(request, 'granadilla/photo_delete.html', RequestContext(request, {
            'object': user,
        }))


@login_required
def user(request, uid):
    user = get_object_or_404(models.LdapUser, pk=uid)

    # set permissions
    can_edit = can_write(request.user, user)

    # handle form
    if request.method == 'POST':
        if not can_edit:
            raise PermissionDenied
        form = LdapUserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect(reverse(index))
    else:
        form = LdapUserForm(instance=user)

    context = ({
        'can_edit': can_edit,
        'object': user,
        'form': form,
    })

    return render(request, 'granadilla/user.html', context)


@login_required
def user_card(request, uid):
    user = get_object_or_404(models.LdapUser, pk=uid)
    return user_vcard(user)

granadilla/templates/granadilla/base.html
{% extends "base.html" %}
{% load granadilla_tags %}
{% load i18n static %}

{% block title %}{% block subtitle %}{% endblock %} | {% granadilla_title %}{% endblock %}

{% block headextra %}
<link rel="stylesheet" type="text/css" href="{% static "granadilla/css/granadilla.css" %}" />
{% endblock %}

{% block branding %}<h1 id="site-name">{% autoescape off %}{% granadilla_version %}{% endautoescape %}</h1>{% endblock %}

{% block related %}
<div class="module">
<h2>{% granadilla_title %}</h2>
<ul>
  <li class="phonebook-user"><a href="{% url "granadilla:index" %}">{% trans "Users" %}</a></li>
  <li class="phonebook-group"><a href="{% url "granadilla:groups" %}">{% trans "Groups" %}</a></li>
  <li class="phonebook-device"><a href="{% url "granadilla:device_list" %}">{% trans "Devices" %}</a></li>
  <li class="password-change"><a href="{% url "granadilla:change_password" %}">{% trans "Change password" %}</a></li>
{% block links %}{% endblock %}
</ul>
</div>
{% endblock %}

granadilla/templates/granadilla/change_password.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %} {{user.username}} {% endblock %}

{% block breadcrumbs %}<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; {{user.username}} &rsaquo; {% trans "Password change" %} {% endblock %}

{% block headextra %}
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
{% endblock %}

{% block content %}

<form action="" method= "POST">
<table class="modulepass">
{% csrf_token %}
<caption>{{ user.username }}</caption>
		<tr>
			{{form}}
			{{ form.media }}
		</tr>
		<tr>
			<td>&nbsp;</td> <td><input id="buttonpassword" type="submit" value="{% trans "Change password" %}"> </td>
		</tr>

</table>
</form>

{% endblock %}

granadilla/templates/granadilla/device.html
{% extends "granadilla/device_base.html" %}
{% load i18n %}

{% block content %}
<form method="POST">
{% csrf_token %}
<table class="module">
<caption>{% if object %}{{ object }}{% else %}{% trans "Add a device" %}{% endif %}</caption>
{% if form.errors %}
    {% for field, error in form.errors.items %}
        <div class="alert alert-error">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<table class="device">
{{ form }}

<tr>
  <td>&nbsp;</td>
  <td><button type="submit">{% if object %}{% trans "Modify" %}{% else %}{% trans "Add" %}{% endif %}</button><a href="{% url "granadilla:device_list" %}"><button type="button">{% trans "Cancel" %}</button></a>
  </td>
</tr>
</table>
</form>
{% endblock %}

granadilla/templates/granadilla/device_attr.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{% trans "Devices" %}{% endblock %}

{% block breadcrumbs %}
<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; {% trans "Devices" %}
{% endblock %}

{% block content %}
<h2>{% trans "Device details" %}</h2>

<table class="phonebook">
  <tbody>
    <tr>
      <th>{% trans "Owner" %}</th>
      <td>{{ device.owner_username }}</td>
    </tr>
    <tr>
      <th>{% trans "Name" %}</th>
      <td>{{ device.name }}</td>
    </tr>
    <tr>
      <th>{% trans "Login" %}</th>
      <td>{{ device.login }}</td>
    </tr>
    <tr>
      <th>{% trans "Password" %}</th>
      <td><a href="{% url "granadilla:device_password" device.login %}">{% trans "Regenerate password" %}</a></td>
    </tr>
  </tbody>
</table>

{% endblock %}

granadilla/templates/granadilla/device_base.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{% if object %}{{ object }}{% else %}{% trans "New device" %}{% endif %}{% endblock %}

{% block breadcrumbs %}<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; <a href="{% url "granadilla:device_list" %}">{% trans "Devices" %}</a> &rsaquo; {% if object %}{{ object }}{% else %}{% trans "New device" %}{% endif %}{% endblock %}

granadilla/templates/granadilla/device_delete.html
{% extends "granadilla/device_base.html" %}
{% load i18n %}

{% block content %}

{% if object %} 

<h1>{% blocktrans %}Delete {{ object }}{% endblocktrans %}</h1>
{% blocktrans %}Are you sure you want to delete {{ object }}?{% endblocktrans %}

<form method="POST">
{% csrf_token %}
<input type="submit" value="{% trans "Yes" %}" />
</form>

<form action="{% url "device_list" %}" method="GET">
{% csrf_token %}
<input type="submit" value="{% trans "No" %}" />
</form>

{% else %}
<p>{% trans "This device does not exist." %}</p>
<a href="{% url "granadilla:device_list" %}">{% trans "Back to the device list" %}</a>

{% endif %}

{% endblock %}

granadilla/templates/granadilla/device_list.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{% trans "Devices" %}{% endblock %}

{% block breadcrumbs %}
<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; {% trans "Devices" %}
{% endblock %}

{% block content %}
<h2>{% trans "Devices" %}</h2>

<a href="{% url "granadilla:device_create" %}">{% trans "Add a device" %}</a>

{% if object_list %}

<table class="phonebook">
  <thead>
    <tr>
      <th>{% trans "Owner" %}</th>
      <th>{% trans "Device login" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for device in devices %}
    <tr>
      <td>{{ device.owner_username }}</td>
      <td><a href="{% url "granadilla:device_details" device.login %}">{{ device.login }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}
<p>{% trans "You do not have any devices yet." %}</p>
{% endif %}

{% endblock %}

granadilla/templates/granadilla/device_password.html
{% extends "granadilla/device_base.html" %}
{% load i18n %}

{% block content %}

{% if password %} 

<h1>{% blocktrans %} Generated password for {{ device.login }}{% endblocktrans %}</h1>
{% trans "The device's password is now: " %} {{ password }}

{% else %}
<form method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans "Generate new password" %}" />
</form>
{% endif %}

<a href="{% url "granadilla:device_list" %}">{% trans "Back to the device list" %}</a>

{% endblock %}

granadilla/templates/granadilla/group.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{{ group }}{% endblock %}

{% block breadcrumbs %}
{% if home %}
{% granadilla_title %}
{% else %}
<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; <a href="{% url "granadilla:groups" %}">{% trans "Groups" %}</a> &rsaquo; {{ group }}
{% endif %}
{% endblock %}

{% block content %}
<h2>{{ group }}</h2>

{% if members %}

{% if printable %}

<table class="phonebook">
  <thead>
    <tr>
      <th></th>
      <th>{% trans "phone" %}</th>
      <th>{% trans "mobile phone" %}</th>
      <th>{% trans "internal phone" %}</th>
    </tr>
  </thead>
  <tbody>
{% for member in members %}
    <tr>
      <td class="name"><a href="{% url "granadilla:user" member.pk %}">{{ member }}</a></td>
      <td class="phone">{{ member.phone|default_if_none:"-" }}</td>
      <td class="phone">{{ member.mobile_phone|default_if_none:"-" }}</td>
      <td class="phone">{{ member.internal_phone|default_if_none:"-" }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% else %}

{% for member in members %}
<div class="card">
  <div class="name">
    <a href="{% url "granadilla:user" member.pk %}">{{ member }}</a>
  </div>
  <div class="photo">
    <div class="centering">
      <a href="{% url "granadilla:user" member.pk %}"><img src="{% if member.photo %}{% url "granadilla:photo" member.pk %}{% else %}{% granadilla_media 'img/unknown.png' %}{% endif %}" alt="{{ member }}" /></a>
    </div>
  </div>
  {% if member.mobile_phone %}
  <div class="mobile">{{ member.mobile_phone }}</div>
  {% endif %}
</div>
{% endfor %}

<div class="clear"></div>

{% endif %}

{% else %}
<p>{% trans "There are no users in this group." %}</p>
{% endif %}

{% endblock %}

{% block links %}
<li class="phonebook-image">
{% if printable %}
  <a href="{% url "granadilla:group" group.name %}">{% trans "Show photos" %}</a>
{% else %}
  <a href="{% url "granadilla:group_print" group.name %}">{% trans "Show list" %}</a>
{% endif %}
</li>
{% endblock %}

granadilla/templates/granadilla/group_list.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{% trans "Groups" %}{% endblock %}

{% block breadcrumbs %}<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; {% trans "Groups" %}{% endblock %}

{% block content %}
<h2>{% trans "Groups" %}</h2>

{% if object_list %}

<ul>
{% for group in object_list %}
<li><a href="{% url "granadilla:group" group.name %}">{{ group }}</a></li>
{% endfor %}
</ul>

{% else %}

<p>There are no groups yet.</p>

{% endif %}
{% endblock %}

granadilla/templates/granadilla/photo_delete.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}

{% block subtitle %}{{ object }}{% endblock %}

{% block breadcrumbs %}<a href="{% url "granadilla:index" %}">Phonebook</a> &rsaquo; {{ object }}{% endblock %}

{% block content %}
<table class="module">
<caption>Remove photo</caption>
<tr>
<td>
  <img src="{% url "granadilla:photo" object.pk %}"/>
</td>
<td>
  <form method="POST">
  {% csrf_token %}
  Are you sure you want to delete the photo for {{ object }}?
  <br/>
  <input type="submit" value="Yes, I'm sure" />
  </form>
  <form action="{% url "granadilla:index" %}" method="GET">
  {% csrf_token %}
  <input type="submit" value="No, I'm not sure" />
  </form>
</td>
</tr>
</table>
{% endblock %}

granadilla/templates/granadilla/user.html
{% extends "granadilla/base.html" %}
{% load granadilla_tags %}
{% load i18n %}

{% block subtitle %}{{ object }}{% endblock %}

{% block breadcrumbs %}<a href="{% url "granadilla:index" %}">{% granadilla_title %}</a> &rsaquo; {{ object }}{% endblock %}

{% block content %}
<table class="module">
<caption>{{ object }}</caption>
<tr>
<td>
  <img src="{% if object.photo %}{% url "granadilla:photo" object.pk %}{% else %}{% granadilla_media 'img/unknown.png' %}{% endif %}"/>
{% if object.photo and can_edit %}
  <p>
    <a href="{% url "granadilla:photo_delete" object.pk %}">{% trans "Remove photo" %}</a>
  </p>
{% endif %}
</td>
<td>
  <form enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  <table>
  <tr>
    <th>{% trans "Email" %}:</th>
    <td><a href="mailto:{{ object.email }}">{{ object.email }}</a></td>
  </tr>
{% if can_edit %}
  {{ form }}
  <tr>
    <td>&nbsp;</td><td><input type="submit"/></td>
  </tr>
{% else %}
  {% for f in form %}
  {% ifnotequal f.name "photo" %}
  <tr>
    <th>{{ f.label }}:</th>
    <td>{% field_value f %}</td>
  </tr>
  {% endifnotequal %}
  {% endfor %}
{% endif %}
  <tr>
    <th>vCard:</th>
    <td><a href="{% url "granadilla:user_card" object.pk %}">{% trans "Download" %}</a></td>
  </tr>
  </table>
  </form>
</td>
</tr>
</table>
{% endblock %}